### ISSUE TITLE
URI redirect to HTTP?

### ISSUE THREAD

**Issue by nanexcool** [stevenmaguire/oauth2-bitbucket#1]
I'm getting a "cURL error 60: SSL certificate problem: unable to get local issuer certificate" because I'm redirecting to an http hosted page instead of https. Is there a setting I can change to allow for this?

**Comment by stevenmaguire** [comment]
This issue is likely a configuration issue on the server that is hosting your project, not this package. 

I did a little bit of googling for you. 

https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/replies/52954

https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/replies/37017

http://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by nanexcool** [comment]
Thank you! Second link provided the answer.

**Comment by stevenmaguire** [comment]
Great!
